# Site settings
title:          Sunho's blog
description:    "Study note"
baseurl:        ""
url:            "https://sunhosong.github.io"

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

#disqus
disqus-shortname: "sunhosong"
